project:
  type: website

website:
  title: "CTBrowser Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - privacy_policy.qmd
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
